Update perft_test.yml

diff --git a/.github/workflows/perft_test.yml b/.github/workflows/perft_test.yml
--- a/.github/workflows/perft_test.yml
+++ b/.github/workflows/perft_test.yml
@@ -13,25 +13,26 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
+      - name: Install Clang
+        run: sudo apt-get install -y clang
+
       - name: Install Stockfish
         run: |
           sudo apt-get update
           sudo apt-get install -y stockfish
 
-      - name: Install CMake
+      - name: Set up CMake with Clang
         run: |
           sudo apt-get update
-          sudo apt-get install -y wget
-          wget https://cmake.org/files/v3.27/cmake-3.27.9-linux-x86_64.sh
-          sudo sh cmake-3.27.0-Linux-x86_64.sh --prefix=/usr/local --skip-license
-          sudo rm cmake-3.27.0-Linux-x86_64.sh
+          sudo apt-get install -y cmake
+          export CXX=clang++
+          cmake ..
 
       - name: Build Chess Engine
         run: |
           mkdir build
           cd build
-          cmake ..
-          make || exit 1 # Fail the action if make fails
+          make || exit 1  # Fail the action if make fails
 
       - name: Run Perft Test
         run: |
